spring:
  application:
    name: group-selector
tg:
  groups:
    - https://t.me/+HAQp24w7NIFlNjEy
    - https://t.me/+d1z7qeCzeUNkZmI6
    - https://t.me/+Op6Lq8K5VUE5YmU6
    - https://t.me/+sMRKLnKwRSU3MjBi
    - https://t.me/+x678FWKHi0BiMjBi




